openapi: 3.0.0
info:
  title: Простое API авторизации
  version: 1.0.0
servers:
  - url: http://localhost/server_api/api/v1/
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        password:
          type: string
paths:
  /auth.php:
    get:
      summary: Проверка авторизации
      description: Проверяет, авторизован ли пользователь.
      responses:
        '200':
          description: Успешный ответ с сообщением о статусе авторизации
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: Пользователь не авторизован
          content:
            text/plain:
              schema:
                type: string
    post:
      summary: Авторизация пользователя
      description: Позволяет пользователю войти в систему.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: admin
                password:
                  type: string
                  example: password
      responses:
        '200':
          description: Успешная авторизация
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: Неверные учетные данные
          content:
            text/plain:
              schema:
                type: string
    delete:
      summary: Выход из системы
      description: Позволяет пользователю выйти из системы.
      responses:
        '200':
          description: Успешный выход
          content:
            text/plain:
              schema:
                type: string
